-- 입양 날짜 구하기

SELECT HOUR(DATETIME) AS HOUR,  COUNT(HOUR(DATETIME)) FROM ANIMAL_OUTS 
GROUP BY HOUR HAVING HOUR >= 9 AND HOUR <= 19  ORDER BY HOUR

-- DATETIME형식이 2022-01-26 11:55:00 와 같은 형식이어서 컬럼내용을 변경해야하나..? 고민했으나 HOUR 함수가 있었다ㅎ