-- 없어진 기록 찾기
SELECT ANIMAL_ID,NAME FROM ANIMAL_OUTS 
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS) ORDER BY ANIMAL_ID

-- NOT IN을 쓰면 아주 간단하게 해결될 문제....


-- LEFT JOIN 사용하기

SELECT A.ANIMAL_ID,A.NAME FROM ANIMAL_OUTS A 
LEFT JOIN ANIMAL_INS B ON A.ANIMAL_ID = B.ANIMAL_ID 
WHERE B.ANIMAL_ID IS NULL ORDER BY A.ANIMAL_ID